### ISSUE TITLE
About replacing different backbones

### ISSUE THREAD

**Issue by Des-Moines-38** [SJTU-Quant/LIFT#13]
Thanks for your interesting work first!
When I want to replace my own backbone,where do I need to revise ? Except dropping my model into models and revising hyperparameter?

**Comment by MogicianXD** [comment]
After dropping your model file (e.g., `Somemodel.py`) into the directory `/models`, 
**just set the argument `--model Somemodel`** in your scripts.

Then your model will be initialized by [this line](https://github.com/SJTU-DMTai/LIFT/blob/79cf8f157bb9a616c9733daf1e9c2cfefdc98c94/exp/exp_main.py#L40)
```                
model = importlib.import_module(f'models.{self.args.model}').Model(self.args).float()
``` 

Next, our code will wrap your backbone into our LIFT framework automatically.

**Comment by MogicianXD** [comment]
In our experiments, the backbones only take the lookback window as input. If you want to take more (e.g., timestamp), you can revise the [forward function](https://github.com/SJTU-DMTai/LIFT/blob/79cf8f157bb9a616c9733daf1e9c2cfefdc98c94/models/LIFT.py#L32) as
```
    def forward(self, x, *args, leader_ids=None, shift=None, r=None, y_hat=None):
        if y_hat is None:
            y_hat = self.backbone(x, *args)
```
