### ISSUE TITLE
About the script of Crossformer on PeMSD8.sh

### ISSUE THREAD

**Issue by hniujc** [SJTU-Quant/LIFT#3]
Very interesting paper! Would you provide the script of Crossformer on PeMSD8? Thank you!

**Comment by MogicianXD** [comment]
You can try this:
```bash
itr=1
seq_len=336
data=PeMSD8
model_name=Crossformer
train_epochs=100
learning_rate=0.001

for pred_len in 24 48 96 192 336 720
do
  python -u run_longExp.py \
    --dataset $data --model $model_name --seq_len $seq_len --pred_len $pred_len \
    --learning_rate $learning_rate > logs/backbone/$model_name'_'$data'_'$pred_len'_lr'$learning_rate.log 2>&1
done
```

We will rerun hyperparameter tuning these days. The results reported in the paper will be updated soon.

**Comment by MogicianXD** [comment]
We have uploaded our scripts for Crossformer and Crossformer+LIFT in the latest [commit](https://github.com/SJTU-Quant/LIFT/commit/49c630ab0d4bfcb7e3d81d752e5f3716692a3918). The paper has also been updated.

**Comment by hniujc** [comment]
Thank you very much for the scripts!
