### ISSUE TITLE
Inconsistent results in appendix of the paper

### ISSUE THREAD

**Issue by Dutch-voyage** [SJTU-Quant/LIFT#8]
I notice the results of PatchTST on ETTh1 in Appedix Table 4 and Table 5 are inconsistent.
![d64853e89365149e85ed5bf13dc53a39](https://github.com/user-attachments/assets/86126c00-bde4-40b6-aafb-2489a11e78a0)
![98e919d0f2330566ac61e05b841f54b7](https://github.com/user-attachments/assets/7ed9099a-3e99-4a43-9ed8-ea23b80152e4)
Is this mistypo or something? if so, can you provide the correct ones as baseline results for future study?

**Comment by MogicianXD** [comment]
Sorry, we misplaced the results of $H\in \{96, 192, 336, 720\}$ by those of $H\in \{24, 48, 96, 192\}$. We will correct them in ArXiv soon. 

Thank you for pointing it out! 

The correct results are provided below.
![image](https://github.com/user-attachments/assets/de0c85c2-29f6-4177-8bcb-997c0fa40f00)

**Comment by MogicianXD** [comment]
By the way, we follow the benchmark settings of DLinear, where the test dataloader does not drop the last batch. Yet, PatchTST drops its last batch. We just copied the results reported in the paper of PatchTST. Our released code in this repo may give different results for PatchTST.

**Comment by MogicianXD** [comment]
By the way, we follow the benchmark settings of DLinear, where the test dataloader does not drop the last batch. Yet, PatchTST drops its last batch. We just copied the results reported in the paper of PatchTST. Our released code in this repo may give different results for PatchTST.

**Comment by Dutch-voyage** [comment]
Thanks for your reply! Dropping the last batch proves to a bug that affects fair evaluation on small datasets in this work: https://github.com/VEWOXIC/FITS
It's good to hear your results follow a correct setting.
